# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  wisecrm:
    image: wisecrm
    build:
      context: .
      dockerfile: WiseCRM/Dockerfile
    ports:
      - 5108:5108
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
